package com.blob.enums;

public enum SessionParamEnum {
	USER,
	LAST_LOGGED_IN,
	SERVICE,
	SERVICES,
	TAB,
	NO_OF_UNREAD_MESSAGES,
	NO_OF_SHORTLISTED_PROFILES,
	PROFILE_SEARCH_CURRENT_PAGE_NO
}
